// English workspace labels. User-authored names and task content stay unchanged.
const workspaceEnglish = <String, String>{
  '표시 설정을 저장하지 못했습니다. 다시 시도해 주세요.':
      'Could not save your display preferences. Try again.',
  '바로가기': 'Shortcuts',
  '바로가기 검색': 'Search shortcuts',
  '바로가기 {v0}개': '{v0} shortcuts',
  '등록된 바로가기': 'Added shortcuts',
  '도구 추가': 'Add tools',
  '도구 찾기': 'Find tools',
  '추천 도구': 'Suggested tools',
  '팀 주소를 등록해 브라우저에서 여세요.': 'Add your team’s URL to open it in your browser.',
  '팀 도구와 자료의 바로가기를 관리하세요.':
      'Manage shortcuts to your team’s tools and resources.',
  '사이트 아이콘': 'Site icon',
  '아이콘 찾는 중…': 'Finding icon…',
  '사이트 아이콘을 가져왔습니다.': 'Site icon found.',
  '사이트 아이콘을 찾지 못해 기본 아이콘을 사용합니다.':
      'No site icon found. Using the default icon.',
  '아이콘 다시 찾기': 'Find icon again',
  '기본 아이콘 사용': 'Use default icon',
  '바로가기 추가됨': 'Shortcut added',
  '추가': 'Add',
  '도구 {v0}개': '{v0} tools',
  '등록 {v0}개': '{v0} added',
  '팀 폴더나 채팅방 주소를 입력해 바로가기를 추가하세요.':
      'Enter a team folder or chat URL to add a shortcut.',
  '선택한 서비스 아이콘을 사용합니다.': 'Using the selected service’s icon.',
  '주소를 입력하면 사이트 아이콘을 자동으로 가져옵니다.':
      'The site icon is fetched automatically when you enter a URL.',
  '문서': 'Documents',
  '작업 관리': 'Task management',
  '커뮤니케이션': 'Communication',
  '개발': 'Development',
  '디자인': 'Design',
  '팀 링크': 'Team links',
  '기본 도구': 'Built-in tools',
  '서비스 홈': 'Service home',
  '팀 주소 설정': 'Set team URL',
  '즐겨찾기': 'Favorites',
  '즐겨찾기에 추가': 'Add to favorites',
  '즐겨찾기에서 제거': 'Remove from favorites',
  '모든 서비스': 'All services',
  '등록 순': 'Added order',
  '이름 순': 'Name',
  '개인별 즐겨찾기와 표시 설정은 이 기기에 저장됩니다.':
      'Your favorites and display settings are saved on this device.',
  '기본 도구는 서비스 홈을 엽니다. 팀 폴더나 채팅방 주소로 변경하세요.': 'Built-in tools open the service home. Set a team folder or chat URL to link your team’s space.',
  '주소에 맞는 서비스가 자동으로 선택됩니다.': 'The service is detected from the URL.',
  '팀 채팅과 오픈채팅': 'Team chat and open chat',
  '선택한 필터에 해당하는 바로가기가 없습니다.': 'No shortcuts match your filters.',
  '검색어나 서비스 필터를 변경해 보세요.': 'Try a different search or service filter.',
  '즐겨찾기를 저장하지 못했습니다. 다시 시도해 주세요.': 'Could not save your favorites. Try again.',
  '팀에서 사용하는 도구와 자료를 한곳에서 여세요.':
      'Open your team’s tools and resources from one place.',
  '등록된 바로가기가 없습니다.': 'No shortcuts yet.',
  '링크를 추가해 팀 도구와 자료를 연결하세요.': 'Add links to your team’s tools and resources.',
  '다른 이름이나 주소로 검색해 보세요.': 'Try a different name or URL.',
  '바로가기 수정': 'Edit shortcut',
  '바로가기 삭제': 'Delete shortcut',
  '“{v0}” 바로가기를 삭제할까요?': 'Delete the “{v0}” shortcut?',
  '링크 복사': 'Copy link',
  '링크를 복사했습니다.': 'Link copied.',
  '링크를 열지 못했습니다. 주소를 확인해 주세요.':
      'Could not open the link. Check the URL and try again.',
  '바로가기를 저장하지 못했습니다. 다시 시도해 주세요.': 'Could not save the shortcut. Try again.',
  '바로가기 이름을 입력해 주세요.': 'Enter a shortcut name.',
  '바로가기 이름과 주소를 확인해 주세요.': 'Check the shortcut’s name and URL.',
  '올바른 HTTPS 주소를 입력해 주세요.': 'Enter a valid HTTPS URL.',
  '바로가기는 최대 60개까지 추가할 수 있습니다.': 'You can add up to 60 shortcuts.',
  '중복된 바로가기 항목을 확인해 주세요.': 'Check for duplicate shortcuts.',
  '바로가기가 다른 곳에서 변경되었습니다. 최신 내용을 확인한 뒤 다시 저장해 주세요.': 'Someone else updated the shortcuts. Review the latest list before saving again.',
  '변경 사항을 저장하고 있습니다. 잠시 후 다시 시도해 주세요.':
      'Changes are being saved. Try again in a moment.',
  '자주 쓰는 도구': 'Popular tools',
  '팀 폴더, 보드 또는 채팅방의 HTTPS 주소를 입력하세요.':
      'Enter the HTTPS URL of a team folder, board, or chat.',
  '직접 입력': 'Custom',
  '서비스': 'Service',
  '설명 (선택)': 'Description (optional)',
  '카카오톡': 'KakaoTalk',
  '공유 파일과 문서': 'Shared files and documents',
  '팀 문서와 위키': 'Team documents and wikis',
  '이슈와 프로젝트 보드': 'Issues and project boards',
  '팀 채팅과 음성 회의': 'Team chat and voice calls',
  '팀 채팅 · 채팅방 링크로 변경하세요': 'Team chat · Set your chat link',
  '코드와 저장소': 'Code and repositories',
  '디자인과 프로토타입': 'Designs and prototypes',
  '팀 채널과 메시지': 'Team channels and messages',
  "이전": "Previous",
  "다음": "Next",
  "복구 기록": "Recovery history",
  "기록 보기": "View history",
  "전송 기록을 복구했습니다.": "Transmission records recovered.",
  "읽지 못한 기록은 보관했습니다. 저장된 작업을 기준으로 전송을 다시 준비합니다.": "Unreadable records have been preserved. Uploads will be rebuilt from your saved tasks.",
  "복구 기록이 변경되었습니다. 다시 확인해 주세요.":
      "Recovery history has changed. Please review it again.",
  "복구 기록의 정보를 읽을 수 없습니다.": "Could not read this recovery record.",
  "당시 앱에서 지원하지 않는 작업 항목이 포함되어 있었습니다.": "This record contained task fields that the app did not support at the time.",
  "전송 기록의 형식이 올바르지 않아 읽을 수 없었습니다.": "The transmission record could not be read because its format was invalid.",
  "전송 기록을 확인하는 과정에서 문제가 발견되었습니다.":
      "An issue was found while validating the transmission record.",
  "시간 정보 없음": "Time unavailable",
  "전송 대기열": "Upload queue",
  "전송 완료 기록": "Upload receipts",
  "전송 기록": "Transmission record",
  "작업 정보 없음": "Task details unavailable",
  "오류 세부정보": "Error details",
  "오류 내용": "Original error",
  "기록 식별자": "Record ID",
  "읽지 못한 전송 기록의 발생 이유와 원본 오류를 확인할 수 있습니다. 작업 데이터는 복구 과정에서 삭제하지 않습니다.": "Review the reasons and original errors for unreadable transmission records. Task data is preserved during recovery.",
  "총 {v0}건 · {v1}/{v2} 페이지": "{v0} records · Page {v1} of {v2}",
  "보관된 복구 기록이 없습니다.": "No recovery records stored.",
  "작업 데이터에 지원하지 않는 항목이 있습니다.": "The task data contains unsupported fields.",
  "자료": "Resources",
  "작성자": "Created by",
  "파일 추가": "Add file",
  "링크 추가": "Add link",
  "자료 이름": "Resource name",
  "링크 주소": "Link URL",
  "첨부한 자료가 없습니다.": "No resources attached.",
  "목록에서 제거": "Remove from list",
  "링크 열기": "Open link",
  "미리보기": "Preview",
  "접기": "Collapse",
  "다운로드": "Download",
  "이미지": "Image",
  "첨부 파일 한도": "Attachment limit",
  "파일당 최대 용량": "Maximum file size",
  "1~50MB로 설정할 수 있습니다.": "Choose a limit from 1 to 50 MB.",
  "변경한 한도는 새로 첨부하는 파일부터 적용됩니다.": "The limit applies to new attachments.",
  "Markdown 문법을 사용할 수 있습니다.": "Markdown formatting is supported.",
  "담당자는 작업 상세의 전달 기능으로 변경할 수 있습니다.":
      "Use handoff in task details to change the assignee.",
  "파일당 최대 {value0}MB · Markdown 미리보기 지원":
      "Up to {value0} MB per file · Markdown preview available",
  "자료를 처리하지 못했습니다. 다시 시도해 주세요.":
      "Could not process the resource. Please try again.",
  "링크를 열지 못했습니다. 주소를 복사해서 확인하세요.":
      "Could not open the link. Copy the URL to open it in your browser.",
  "프로젝트의 첨부 파일 용량 한도를 초과했습니다.":
      "This file exceeds the project's attachment limit.",
  "첨부 자료를 변경했습니다.": "Updated task resources.",
  "파일을 첨부하려면 저장된 프로젝트를 여세요.": "Open a saved project to attach files.",
  "첨부 파일 내용이 등록 당시와 다릅니다.":
      "The file no longer matches the original attachment.",
  "첨부 파일 내용을 확인하지 못했습니다.": "Could not verify the attachment contents.",
  "첨부 파일을 받으려면 프로젝트 저장소에 연결하세요.":
      "Connect the project repository to download attachments.",
  "작업이 변경되었거나 자료를 수정할 수 없습니다.":
      "This task has changed or you cannot edit its resources.",
  "첨부 자료의 이름과 등록 정보를 확인하세요.": "Check the resource name and attachment details.",
  "첨부 파일 크기 또는 링크 주소를 확인하세요.": "Check the file size or link URL.",
  "작업에는 자료를 최대 30개까지 첨부할 수 있습니다.":
      "You can attach up to 30 resources to a task.",
  "첨부 파일 한도는 관리자만 변경할 수 있습니다.":
      "Only the project administrator can change the attachment limit.",
  "파일 한도가 변경되었습니다. 최신 설정을 확인하세요.":
      "The attachment limit has changed. Refresh the project settings.",
  "첨부 파일을 받지 못했습니다. 연결과 저장소 접근 권한을 확인하세요.": "Could not download the attachment. Check your connection and repository access.",
  "첨부 파일 전송이 완료되지 않았습니다. 다시 동기화하세요.":
      "The attachment upload is incomplete. Sync again to retry.",
  "전송할 첨부 파일이 이 컴퓨터에 없습니다. 원래 컴퓨터에서 다시 동기화하세요.": "This attachment is not on this computer. Sync it from the computer where it was added.",
  "큰 Markdown 문서는 다운로드해서 확인하세요. 미리보기는 256KB까지 지원합니다.": "Download this large Markdown document to read it. Preview supports up to 256 KB.",
  "흑백": "Monochrome",
  "라이트 모드에서는 검은색, 다크 모드에서는 흰색이 적용됩니다.":
      "Black in light mode, white in dark mode.",
  "{v0} 유지": "Keep {v0}",
  "이번 달에 예정된 작업이 없습니다.  ·  ": "No tasks scheduled this month.  ·  ",
  "고정": "Pinned",
  "해제": "Unpinned",
  "GitHub 계정": "GitHub account",
  "GitHub 저장소": "GitHub repository",
  "JSON 변경안": "JSON changes",
  "{value0}\n다음 담당자: {value1}": "{value0}\nNext assignee: {value1}",
  "{value0} · {value1} 요청": "{value0} · {value1} request",
  "{value0} · 검토 요청": "{value0} · Review requested",
  "{value0} · 관련 업무": "{value0} · Related tasks",
  "{value0} 요청": "{value0} request",
  "{value0} 전체": "All {value0}",
  "{value0} 홈": "{value0} home",
  "{value0}개 읽지 않음": "{value0} unread",
  "{value0}개 작업": "{value0} tasks",
  "{value0}건": "{value0}",
  "{value0}님만 수정 가능": "Only {value0} can edit",
  "{value0}에게 전달했습니다. {value1}.": "Assigned to {value0}. {value1}.",
  "{value0}으로 변경했습니다.": "Changed to {value0}.",
  "“{value0}”\n\n목록·칸반·일정에서 삭제됩니다. GitHub 동기화 후 팀에도 반영됩니다. 앱에서 복원할 수 없습니다.": "“{value0}”\n\nThis task will be removed from the list, board, and schedule. The deletion will be shared with your team after GitHub sync. This cannot be undone in the app.",
  "가입 승인 대기 중입니다. 관리자가 참여를 승인하면 작업을 진행할 수 있습니다.": "Your membership is awaiting approval. You can work on tasks once an administrator approves your request.",
  "개인 변경안을 JSON 파일로 내보냈습니다.": "Your local changes have been exported as JSON.",
  "검색어나 필터를 바꾸어 보세요.": "Try a different search or adjust your filters.",
  "검토 담당자": "Reviewer",
  "계정": "Account",
  "관리자": "Administrator",
  "권한": "Permissions",
  "기록 없음": "No record",
  "나만 수정하도록 잠금": "Lock editing to me",
  "내 변경: {value0}\n통합본: {value1}":
      "My changes: {value0}\nMerged data: {value1}",
  "내 알림": "My notifications",
  "내 할 일": "My tasks",
  "내보내기 실패: {value0}": "Export failed: {value0}",
  "높은 우선순위": "High priority",
  "다른 작업 처리": "More task actions",
  "다음 페이지": "Next page",
  "닫기": "Close",
  "담당 · {value0}": "Assignee · {value0}",
  "담당자": "Assignee",
  "데이터 저장 위치": "Data location",
  "데이터는 변경하지 않았습니다. 양쪽 변경을 확인해 주세요.":
      "No data was changed. Review both versions before continuing.",
  "동작": "Actions",
  "등록 파트": "Original team",
  "로컬": "Local",
  "로컬 작업 공간": "Local workspace",
  "마감 {value0}": "Due {value0}",
  "마감 미정": "No due date",
  "마감 지남": "Overdue",
  "마감일": "Due date",
  "마감일순": "Due date",
  "마지막 전달자": "Last sender",
  "모든 마감일": "All due dates",
  "모든 상태": "All statuses",
  "모든 작업자": "All members",
  "모든 파트": "All teams",
  "모든 프로젝트": "All projects",
  "목록": "List",
  "미정": "Not set",
  "반영 중…": "Applying…",
  "배정받은 작업이 생기면 여기에 표시됩니다.": "Tasks assigned to you will appear here.",
  "변경": "Changes",
  "변경안 내보내기": "Export changes",
  "보관한 작업이 없습니다": "No archived tasks",
  "보관함": "Archive",
  "보관함에서 복원": "Restore from archive",
  "보관함으로 이동": "Archive task",
  "보드": "Board",
  "복원": "Restore",
  "비활성화": "Deactivate",
  "비활성화된 참여자는 작업·업로드가 제한됩니다.":
      "Inactive members cannot edit tasks or upload changes.",
  "비활성화된 참여자입니다. 관리자에게 활성화를 요청하세요.":
      "Your membership is inactive. Ask an administrator to reactivate it.",
  "삭제": "Delete",
  "삭제된 작업입니다.": "This task has been deleted.",
  "삭제된 작업입니다. 변경 기록은 타임라인에서 확인할 수 있습니다.": "This task has been deleted. Its change history is available in the timeline.",
  "상단 고정 해제": "Unpin",
  "상단에 고정": "Pin to top",
  "상태": "Status",
  "상태 · 전달 기록": "Status and handoff history",
  "새 버전을 확인하고 다운로드합니다.": "Check for updates and download the latest version.",
  "새 작업": "New task",
  "새 작업 등록": "Create task",
  "새 작업을 등록해 팀과 함께 진행하세요.": "Create a task to start working with your team.",
  "설명": "Description",
  "설정되지 않음": "Not configured",
  "설정됨 · {value0}": "Configured · {value0}",
  "세부 상태": "Detailed status",
  "수동 JSON은 GitHub에서 검증된 통합본과 다릅니다. 출처를 확인한 파일만 가져오세요. 현재 프로젝트의 업무 데이터가 변경되며 충돌은 자동 덮어쓰지 않습니다.": "Manually imported JSON is not verified through GitHub. Only import files from a trusted source. Importing updates this project’s task data; conflicting changes will not be overwritten automatically.",
  "수동 가져오기 · 내보내기": "Manual import and export",
  "수정 작업": "Revision",
  "시작": "Start",
  "시작일": "Start date",
  "신규 작업": "New task",
  "신뢰할 수 있는 통합본인가요?": "Do you trust this merged data?",
  "알림 미리보기": "Notification preview",
  "알림 열기": "Open notification",
  "알림을 읽음으로 표시하지 못했습니다. 다시 시도해 주세요.":
      "Could not mark the notification as read. Try again.",
  "앱 정보": "About",
  "연결": "Connections",
  "연결되지 않음": "Not connected",
  "오늘 마감": "Due today",
  "완료": "Done",
  "완료일": "Completed on",
  "요청 유형": "Request type",
  "우선순위": "Priority",
  "우선순위순": "Priority",
  "이 작업을 찾을 수 없습니다. 최신 프로젝트 기록을 확인해 주세요.":
      "Task not found. Refresh the project to load the latest changes.",
  "이 작업을 해당 열로 전달할 수 없습니다.": "This task cannot be moved to that column.",
  "이 작업의 프로젝트를 열 수 없습니다. 프로젝트 연결을 확인해 주세요.":
      "Could not open this task’s project. Check the project connection.",
  "이 컴퓨터에서 연결한 프로젝트에 새 이름이 반영됩니다. GitHub 계정은 바뀌지 않습니다.": "Your new name will appear in projects connected on this computer. Your GitHub account will stay the same.",
  "이 컴퓨터의 작업과 전송 대기열을 보관합니다.":
      "Tasks and pending uploads are stored on this computer.",
  "이 프로젝트에서 부여받은 권한입니다.": "Your permissions in this project.",
  "이름": "Name",
  "이름 / 닉네임": "Name or nickname",
  "이름 반영 중…": "Updating name…",
  "이름 변경": "Change name",
  "이름 저장 실패 · 초안은 유지됩니다. {value0}":
      "Could not save your name. Your draft has been kept. {value0}",
  "이름순": "Name",
  "이름을 변경했습니다.": "Name updated.",
  "이름을 입력하세요.": "Enter a name.",
  "이음 버전": "Ieum version",
  "이전 상태 필터": "Previous status filter",
  "이전 페이지": "Previous page",
  "일정": "Schedule",
  "읽기 전용 · 수동 가져오기 권한이 없습니다.":
      "Read only · You do not have permission to import data manually.",
  "읽기 전용 · 수동 가져오기는 작업 변경 권한이 필요합니다.":
      "Read only · Task editing permission is required for manual imports.",
  "임시 작업 공간": "Temporary workspace",
  "자동 동기화를 사용할 수 없을 때": "When automatic sync is unavailable",
  "작성 기록": "Creation details",
  "작성된 설명이 없습니다.": "No description provided.",
  "작성일": "Created on",
  "작업": "Tasks",
  "작업 검색": "Search tasks",
  "작업 배정, 검토 요청, 검토 결과를 확인합니다.":
      "View task assignments, review requests, and review outcomes.",
  "작업 삭제": "Delete task",
  "작업 상세 닫기": "Close task details",
  "작업 상세에서 보관한 항목을 여기서 확인하고 복원할 수 있습니다.": "Tasks archived from the task details appear here. You can restore them at any time.",
  "작업 알림": "Task notification",
  "작업 없음": "No tasks",
  "작업 정보": "Task details",
  "작업을 보관함으로 옮겼습니다.": "Task archived.",
  "작업을 복원했습니다.": "Task restored.",
  "작업을 삭제할까요?": "Delete this task?",
  "작업을 삭제했습니다.": "Task deleted.",
  "잠금": "Editing lock",
  "잠금 해제": "Unlock",
  "재개": "Resume",
  "저장하지 않은 변경사항": "Unsaved changes",
  "저장한 작업의 변경사항을 여기서 확인할 수 있습니다.": "Changes to saved tasks appear here.",
  "전달": "Handoff",
  "전달 경로 선택": "Choose a handoff route",
  "전달 메시지": "Handoff message",
  "전달받은 작업": "Received tasks",
  "전송 전 변경": "Pending changes",
  "전송할 변경이 없습니다.": "No changes to upload.",
  "전체 {value0}": "Total {value0}",
  "전체 {value0}개 목록에서 보기": "View all {value0} in the list",
  "전체 작업": "All tasks",
  "참여 중인 모든 프로젝트에서 사용하는 표시 이름입니다.":
      "Your display name across all projects you belong to.",
  "첫 작업을 등록하기 전에 팀에서 사용할 파트를 추가하세요.":
      "Add your project’s teams before creating the first task.",
  "최근 수정순": "Recently updated",
  "최초 담당자": "Original assignee",
  "최초 작성자": "Created by",
  "출처 확인 · 가져오기": "Confirm source and import",
  "취소": "Cancel",
  "타임라인": "Timeline",
  "테스트 사용자": "Test user",
  "통합 전 확인이 필요해요": "Review before merging",
  "통합본 JSON": "Merged JSON",
  "통합본 가져오기": "Import merged data",
  "통합본 가져오기 실패: {value0}": "Import failed: {value0}",
  "통합본은 10MB 이하만 지원합니다.": "The import file must be 10 MB or smaller.",
  "통합본을 반영했습니다. 개인 변경은 보존했습니다.":
      "Merged data imported. Your local changes have been kept.",
  "팀의 작업 데이터를 공유하는 저장소입니다.":
      "The repository that stores your team’s shared task data.",
  "파트": "Team",
  "표시 이름과 별개의 로그인 식별자입니다.":
      "Your sign-in identifier, separate from your display name.",
  "표시할 작업이 없습니다": "No tasks to display",
  "프로젝트": "Projects",
  "프로젝트 관리자에게 작업을 등록할 파트 추가를 요청하세요.":
      "Ask a project administrator to add a team before creating tasks.",
  "프로젝트 이름": "Project name",
  "프로젝트 저장소에 연결하면 동기화 상태와 전송 대기열을 확인할 수 있습니다.":
      "Connect a project repository to view sync status and pending uploads.",
  "프로젝트 필요": "Project required",
  "프로젝트 현황": "Project overview",
  "프로젝트를 연결하면 파트를 관리할 수 있습니다.": "Connect a project to manage its teams.",
  "프로젝트에 로그인하면 참여자와 파트, 가입 요청을 관리할 수 있습니다.":
      "Sign in to the project to manage members, teams, and join requests.",
  "필터 초기화": "Reset filters",
  "현재 열려 있는 프로젝트입니다.": "The project currently open in this workspace.",
  "현재 작업을 이 단계로 전달할 수 없습니다.": "This task cannot be moved to this stage.",
  "현재 참여 상태": "Membership status",
  "현재 프로젝트": "Current project",
  "확인중 → 진행중 → 검토중 → 완료. 전달하면 확인중으로 이동하며, 보류와 드랍에서 복귀할 수 있습니다.": "To do → In progress → In review → Done. A handoff moves the task to To do. Tasks on hold or dropped can be resumed.",
  "활동 기록": "Activity",
  "활성화": "Activate",
  "검토": "Review",
  "검토자": "Reviewer",
  "검토중": "In review",
  "낮음": "Low",
  "내 작업": "My tasks",
  "높음": "High",
  "담당 파트": "Assigned team",
  "댓글": "Comment",
  "드랍": "Dropped",
  "등록 시각": "Created at",
  "등록 시작": "Created at",
  "모든 작업": "All tasks",
  "미배정": "Unassigned",
  "보류": "On hold",
  "보류 전 상태": "Previous status",
  "보통": "Normal",
  "상단 고정": "Pinned",
  "수정": "Revision",
  "수정 요청": "Revision request",
  "작성": "Creation",
  "작업 상태": "Status",
  "작업 지정일": "Start date",
  "잠금 담당자": "Lock owner",
  "재작업": "Revision",
  "전달 경로": "Handoff route",
  "전달·검토 기록": "Handoff and review history",
  "직전 전달자": "Previous sender",
  "진행 중": "In progress",
  "진행중": "In progress",
  "처리 목적": "Request type",
  "최근 전환 코멘트": "Latest handoff comment",
  "코멘트": "Comment",
  "할 일": "To do",
  "현재 처리 작업자": "Current assignee",
  "현재 처리 파트": "Current team",
  "확인중": "To do",
};
