import {useEffect,useState} from 'react';
import {LayoutDashboard, CalendarDays, GitPullRequest, Link2, Plus, Search, Bell, ArrowUpRight, ArrowRight, X, Check, Clock3, ChevronDown, Download, Upload, ShieldCheck, GitBranch, MessageCircle, Circle, CheckCircle2, RotateCcw, Play, Send, HardDrive, FolderKanban} from 'lucide-react';
import type {Task,State,Status,Conflict} from './types';

const stages:{id:Status;label:string;color:string}[]=[{id:'todo',label:'할 일',color:'#9b9ca8'},{id:'doing',label:'진행 중',color:'#7160d9'},{id:'review',label:'검토',color:'#d59637'},{id:'rework',label:'재작업',color:'#d46b76'},{id:'done',label:'완료',color:'#5b997d'}];
const priorities={high:'높음',normal:'보통',low:'낮음'};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const shortDate=(date:string)=>date?`${Number(date.slice(5,7))}.${date.slice(8,10)}`:'미정';
const current=(task:Task)=>task.status==='review'?task.reviewerId:task.assigneeId;
type Page='board'|'schedule'|'changes'|'settings';
export default function App(){
  const [state,setState]=useState<State>();const [fatal,setFatal]=useState('');const [page,setPage]=useState<Page>('board');
  const [search,setSearch]=useState('');const [part,setPart]=useState('');const [scope,setScope]=useState('all');
  const [selected,setSelected]=useState<string>();const [form,setForm]=useState<Partial<Task>>();const [reason,setReason]=useState('');
  const [toast,setToast]=useState('');const [busy,setBusy]=useState(false);const [alerts,setAlerts]=useState(false);const [conflicts,setConflicts]=useState<Conflict[]>();
  const [dragging,setDragging]=useState<string>();
  useEffect(()=>{if(!window.ieum){setFatal('Electron 데스크톱 앱에서 열어 주세요.');return;}window.ieum.getState().then(setState).catch(e=>setFatal(e.message));},[]);
  useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(timer);},[toast]);
  useEffect(()=>{function escape(e:KeyboardEvent){if(e.key==='Escape'){setForm(undefined);setSelected(undefined);setAlerts(false);setConflicts(undefined);}}window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape);},[]);
  async function run(work:()=>Promise<void>){if(busy)return;setBusy(true);try{await work();}catch(e){setToast(e instanceof Error?e.message:'처리하지 못했습니다.');}finally{setBusy(false);}}
  if(!state)return <div className="loading"><div className="brand-mark">∞</div><h2>이음</h2><p>{fatal||'작업 공간을 준비하고 있습니다.'}</p></div>;
  const s=state;const person=(id:string)=>s.members.find(m=>m.id===id)!;const profile=person(s.profileId);
  const task=s.tasks.find(t=>t.id===selected);const tasks=s.tasks.filter(t=>(!part||t.part===part)&&(!search||`${t.title} ${t.id} ${t.description}`.toLowerCase().includes(search.toLowerCase()))&&(scope==='all'||scope==='mine'&&current(t)===s.profileId&&t.status!=='done'||scope==='review'&&t.status==='review'&&t.reviewerId===s.profileId));
  const avatar=(id:string)=><span className="avatar" style={{background:person(id).color+'18',color:person(id).color}}>{person(id).initials}</span>;
  function create(){const rule=s.rules[0];setForm({title:'',part:rule.part,assigneeId:rule.assigneeId,reviewerId:rule.reviewerId,priority:'normal',assignedDate:today(),dueDate:'',description:''});}
  function transition(status:Status){if(!task)return;run(async()=>{setState(await window.ieum.transition(task.id,status,s.profileId,reason,task.version));setReason('');setToast(status==='review'?'검토자의 할 일로 옮겼습니다.':status==='done'?'완료 승인과 완료일을 기록했습니다.':status==='rework'?'담당자에게 재작업을 요청했습니다.':'작업을 시작했습니다.');});}
  function canMove(t:Task,status:Status){const worker=profile.id===t.assigneeId||profile.role==='manager';const reviewer=profile.id===t.reviewerId||profile.role==='manager';return status==='doing'&&['todo','rework'].includes(t.status)&&worker||status==='review'&&t.status==='doing'&&worker||['done','rework'].includes(status)&&t.status==='review'&&reviewer;}
  function drop(status:Status,id:string){setDragging(undefined);const t=s.tasks.find(task=>task.id===id);if(!t||t.status===status)return;if(!canMove(t,status)){setToast('담당 역할과 작업 흐름에 맞는 열로 옮겨 주세요.');return;}if(status==='rework'){setSelected(id);setReason('');setToast('재작업 요청 사유를 입력해 주세요.');return;}run(async()=>{setState(await window.ieum.transition(id,status,s.profileId,'',t.version));setToast(`${stages.find(stage=>stage.id===status)?.label} 상태로 옮겼습니다.`);});}
  async function exportChanges(){await run(async()=>{const result=await window.ieum.exportChanges();if(!result.canceled)setToast('개인 변경안을 JSON 파일로 내보냈습니다.');});}
  async function importSnapshot(){await run(async()=>{const result=await window.ieum.importSnapshot();if(result.canceled)return;if(result.applied&&result.state){setState(result.state);setToast('통합본을 반영했습니다. 개인 변경은 보존했습니다.');}else setConflicts(result.conflicts);});}
  const titles={board:['칸반보드','작업의 흐름을 한눈에.'],schedule:['일정 · 작업','담당자와 날짜를 함께 확인하세요.'],changes:['내 변경내역','개인 작업을 팀의 통합본으로 연결하세요.'],settings:['연결 설정','팀의 다음 단계를 준비하세요.']};
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark">∞</div><strong>이음<span>IEUM</span></strong></div>
      <div className="workspace"><div className="workspace-icon"><FolderKanban size={20}/></div><div><strong>졸업작품 팀</strong><small>예시 프로젝트</small></div><ChevronDown size={15}/></div>
      <div className="nav-label">작업 공간</div><nav>{([{id:'board',label:'칸반보드',icon:LayoutDashboard},{id:'schedule',label:'일정 · 작업',icon:CalendarDays},{id:'changes',label:'내 변경내역',icon:GitPullRequest},{id:'settings',label:'연결 설정',icon:Link2}] as const).map(n=><button key={n.id} className={page===n.id?'nav active':'nav'} onClick={()=>setPage(n.id)}><n.icon size={18}/>{n.label}{n.id==='changes'&&s.changes.length>0&&<span className="nav-count">{s.changes.length}</span>}</button>)}</nav>
      <div className="sidebar-note"><div className="local-label"><span/>개인 작업 공간</div><p>내 변경은 이 컴퓨터에 저장돼요.<br/>통합 전까지 팀원에게 반영되지 않아요.</p></div>
      <div className="profile"><div className="profile-top">테스트 사용자 <span>DEMO</span></div><div className="profile-row">{avatar(s.profileId)}<select aria-label="테스트 사용자" value={s.profileId} disabled={busy} onChange={e=>{const id=e.target.value;run(async()=>{setState(await window.ieum.setProfile(id));setToast('테스트 사용자를 변경했습니다.');});}}>{s.members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></div><small>역할을 바꿔 검토 과정을 테스트하세요.</small></div>
    </aside>
    <main><header className="topbar"><span>졸업작품 팀 <span className="slash">/</span> <b>{titles[page][0]}</b></span><div className="top-actions"><span className="prototype">로컬 프로토타입</span><button className="icon-button" aria-label="알림 미리보기" onClick={()=>setAlerts(true)}><Bell size={19}/>{s.notifications.length>0&&<i/>}</button>{avatar(s.profileId)}</div></header>
      <div className="content"><div className="page-heading"><div><div className="eyebrow">TEAM WORKSPACE</div><h1>{titles[page][0]}</h1><p>{titles[page][1]}</p></div><button className="primary" onClick={create}><Plus size={18}/>작업 등록</button></div>
      {(page==='board'||page==='schedule')&&<><div className="stats"><div><span>전체 작업</span><strong>{s.tasks.length}<small>건</small></strong><FolderKanban size={21}/></div><div><span>진행 중</span><strong>{s.tasks.filter(t=>t.status==='doing').length}<small>건</small></strong><Play size={20}/></div><div><span>검토 대기</span><strong>{s.tasks.filter(t=>t.status==='review').length}<small>건</small></strong><ShieldCheck size={21}/></div><div><span>완료</span><strong>{s.tasks.filter(t=>t.status==='done').length}<small>건</small></strong><CheckCircle2 size={21}/></div></div>
        <div className="toolbar"><div className="tabs">{[['all','전체 작업'],['mine','내 할 일'],['review','내 검토 요청']].map(([id,label])=><button className={scope===id?'selected':''} onClick={()=>setScope(id)} key={id}>{label}</button>)}</div><div className="filters"><label className="search"><Search size={16}/><input aria-label="작업 검색" placeholder="작업 검색" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="파트 필터" value={part} onChange={e=>setPart(e.target.value)}><option value="">모든 파트</option>{s.rules.map(r=><option key={r.part}>{r.part}</option>)}</select></div></div>
        <div className="board-caption"><span><Circle size={12}/> 예시 데이터로 흐름을 테스트해 보세요.</span><span>{tasks.length}개 작업 · 자동 저장</span></div>
        {page==='board'?<div className="kanban">{stages.map(stage=><section className={'column '+stage.id+(dragging&&canMove(s.tasks.find(t=>t.id===dragging)!,stage.id)?' drop-allowed':'')} key={stage.id} onDragOver={e=>{if(dragging)e.preventDefault();}} onDrop={e=>{e.preventDefault();drop(stage.id,e.dataTransfer.getData('text/plain'));}}><div className="column-title"><span className="status-dot" style={{background:stage.color}}/><h3>{stage.label}</h3><span className="column-count">{tasks.filter(t=>t.status===stage.id).length}</span><button aria-label={`${stage.label} 작업 등록`} onClick={create}><Plus size={16}/></button></div><div className="cards">{tasks.filter(t=>t.status===stage.id).map(t=><button className="task-card" draggable={!busy} onDragStart={e=>{e.dataTransfer.setData('text/plain',t.id);e.dataTransfer.effectAllowed='move';setDragging(t.id);}} onDragEnd={()=>setDragging(undefined)} key={t.id} onClick={()=>{setSelected(t.id);setReason('');}}><div className="card-meta"><span className="part-tag">{t.part}</span><span className={'priority '+t.priority}>{t.priority==='high'&&'↑ '}{priorities[t.priority]}</span></div><span className="task-id">{t.id.startsWith('TASK-')?'IE-'+t.id.slice(-6).toUpperCase():t.id}</span><h4>{t.title}</h4>{t.status==='rework'&&<p className="rework-snippet">재작업 요청이 있어요</p>}<div className="card-footer"><span className={t.dueDate&&t.dueDate<today()&&t.status!=='done'?'overdue':''}><CalendarDays size={13}/>{shortDate(t.dueDate)}</span><span title={person(current(t)).name}>{avatar(current(t))}</span></div>{t.status==='review'&&<div className="review-line"><ArrowRight size={12}/>{person(t.reviewerId).name} 검토 대기</div>}</button>)}{tasks.filter(t=>t.status===stage.id).length===0&&<div className="empty-column">아직 작업이 없어요</div>}<button className="add-card" onClick={create}><Plus size={14}/>작업 추가</button></div></section>)}</div>:<div className="table-wrap"><table><thead><tr><th>작업내용</th><th>상태</th><th>담당자</th><th>현재 처리자</th><th>우선순위</th><th>작업 지정일</th><th>마감일</th><th>완료일</th></tr></thead><tbody>{tasks.map(t=><tr key={t.id} onClick={()=>setSelected(t.id)}><td><strong>{t.title}</strong><small>{t.part} · {t.id.startsWith('TASK-')?t.id.slice(-6):t.id}</small></td><td><span className={'state-tag '+t.status}>{stages.find(st=>st.id===t.status)?.label}</span></td><td>{person(t.assigneeId).name}</td><td>{person(current(t)).name}</td><td><span className={'priority '+t.priority}>{priorities[t.priority]}</span></td><td>{t.assignedDate}</td><td>{t.dueDate||'—'}</td><td>{t.completedDate||'—'}</td></tr>)}</tbody></table>{!tasks.length&&<div className="empty">조건에 맞는 작업이 없습니다.</div>}</div>}</>}
      {page==='changes'&&<><div className="flow-strip">{['개인 SQLite','변경안 JSON','개인 브랜치 · PR','main 통합본'].map((label,i)=><div key={label}><span>{i+1}</span>{label}{i<3&&<ArrowRight size={15}/>}</div>)}</div><div className="section-heading"><div><h2>통합 전 변경 <span className="count-pill">{s.changes.length}</span></h2><p>기준 통합본: {s.baseRevision} · 커밋과 PR은 아직 연결되지 않았습니다.</p></div><div className="button-row"><button className="secondary" disabled={busy} onClick={importSnapshot}><Upload size={16}/>통합본 가져오기</button><button className="primary" disabled={busy||!s.changes.length} onClick={exportChanges}><Download size={16}/>변경안 내보내기</button></div></div>{!s.changes.length?<div className="empty-panel"><GitPullRequest size={32}/><h3>아직 개인 변경이 없어요</h3><p>작업을 등록하거나 상태를 바꾸면 여기에 표시됩니다.</p></div>:s.changes.map(c=><div className="change-card" key={c.taskId}><div><span className="part-tag">{c.kind==='create'?'신규 작업':'수정 작업'}</span><h3>{c.title}</h3><small>{c.taskId}</small></div><div className="diffs">{c.fields.map(f=><div className="diff" key={f.key}><b>{f.label}</b><span>{f.before||'—'}</span><ArrowRight size={14}/><strong>{f.after||'—'}</strong></div>)}</div></div>)}<div className="info-banner"><ShieldCheck size={18}/><p>같은 항목이 양쪽에서 다르게 변경되면 통합을 멈추고 충돌을 표시합니다. 통합본은 schemaVersion · projectId · revision · tasks 형식입니다.</p></div></>}
      {page==='settings'&&<><div className="integration-grid"><article className="integration"><div className="integration-icon"><GitBranch size={27}/></div><span className="connection-status">앱 연동 예정</span><h2>GitHub</h2><p>개인 브랜치와 PR로 변경을 검토하고,<br/>승인된 통합본을 팀과 공유합니다.</p><div className="repo-name">devbin-lab / ieum</div><button className="secondary" onClick={()=>run(async()=>{await window.ieum.openRepository();})}>저장소 열기<ArrowUpRight size={16}/></button><small>현재는 JSON 내보내기 / 가져오기를 지원합니다.</small></article><article className="integration"><div className="integration-icon discord"><MessageCircle size={27}/></div><span className="connection-status">미연결</span><h2>Discord</h2><p>작업 등록 · 검토 요청 · 재작업 · 완료를<br/>담당자에게 안내할 수 있도록 준비합니다.</p><div className="repo-name">알림 미리보기 {s.notifications.length}건</div><button className="secondary" onClick={()=>setAlerts(true)}>알림 대기 목록 보기<ArrowRight size={16}/></button><small>현재 외부 메시지는 전송하지 않습니다.</small></article></div><div className="section-heading"><div><h2>파트별 기본 배정</h2><p>작업 등록 시 담당 파트에 맞춰 작업자와 검토자가 자동으로 선택됩니다.</p></div></div><div className="table-wrap"><table><thead><tr><th>담당 파트</th><th>기본 작업자</th><th>검토자</th><th>후속 파트 (설계)</th></tr></thead><tbody>{s.rules.map(r=><tr key={r.part}><td><strong>{r.part}</strong></td><td>{person(r.assigneeId).name}</td><td>{person(r.reviewerId).name}</td><td>{r.nextPart||'—'}</td></tr>)}</tbody></table></div><div className="info-banner"><HardDrive size={18}/><p>이 앱은 공유 서버 없이 개인 SQLite를 사용합니다. 후속 파트의 새 작업 생성, GitHub 인증·자동 PR, Discord 전송은 다음 구현 단계입니다.</p></div></>}
      </div><footer><span><span className="tiny-dot"/>SQLite에 자동 저장</span><span>이음 0.1 · 함께 만드는 흐름</span></footer>
    </main>
    {task&&!form&&<div className="overlay" onClick={()=>setSelected(undefined)}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-top"><span className="task-id">{task.id}</span><button className="icon-button" onClick={()=>setSelected(undefined)} aria-label="작업 상세 닫기"><X size={20}/></button></div><span className={'state-tag '+task.status}>{stages.find(st=>st.id===task.status)?.label}</span><h2>{task.title}</h2><div className="detail-grid"><span>담당 파트</span><b>{task.part}</b><span>작업 담당자</span><b>{avatar(task.assigneeId)}{person(task.assigneeId).name}</b><span>검토 담당자</span><b>{avatar(task.reviewerId)}{person(task.reviewerId).name}</b><span>현재 처리자</span><b>{person(current(task)).name}</b><span>우선순위</span><b className={'priority '+task.priority}>{priorities[task.priority]}</b><span>작업 지정일</span><b>{task.assignedDate}</b><span>마감일</span><b>{task.dueDate||'미정'}</b><span>완료일</span><b>{task.completedDate||'—'}</b></div><h3>작업 설명</h3><p className="description">{task.description||'작성된 설명이 없습니다.'}</p>{task.reworkReason&&<div className="reason-box"><b>재작업 요청 사유</b><p>{task.reworkReason}</p></div>}<div className="detail-actions">{(profile.id===task.assigneeId||profile.role==='manager')&&<><button className="secondary" disabled={busy} onClick={()=>setForm({...task})}>작업 수정</button>{['todo','rework'].includes(task.status)&&<button className="primary" disabled={busy} onClick={()=>transition('doing')}><Play size={16}/>작업 시작</button>}{task.status==='doing'&&<button className="primary" disabled={busy} onClick={()=>transition('review')}><Send size={16}/>검토 요청</button>}</>}{task.status==='review'&&(profile.id===task.reviewerId||profile.role==='manager')&&<><button className="primary" disabled={busy} onClick={()=>transition('done')}><Check size={16}/>완료 승인</button><textarea placeholder="재작업이 필요한 이유를 입력하세요" aria-label="재작업 사유" value={reason} onChange={e=>setReason(e.target.value)}/><button className="secondary" disabled={busy||!reason.trim()} onClick={()=>transition('rework')}><RotateCcw size={16}/>재작업 요청</button></>}{task.status==='review'&&profile.id!==task.reviewerId&&profile.role!=='manager'&&<p className="muted">검토자의 확인을 기다리고 있습니다.</p>}</div><h3>활동 기록</h3>{s.activity.filter(a=>a.taskId===task.id).map(a=><div className="activity" key={a.id}><Clock3 size={14}/><div>{person(a.actorId).name} · {a.message}<small>{new Date(a.createdAt).toLocaleString('ko-KR')}</small></div></div>)}</aside></div>}
    {form&&<div className="overlay modal-overlay"><form className="modal" role="dialog" aria-modal="true" aria-label="작업 입력" onSubmit={e=>{e.preventDefault();run(async()=>{setState(await window.ieum.saveTask(form,s.profileId,form.version));setForm(undefined);setToast('작업을 개인 SQLite에 저장했습니다.');});}}><div className="modal-heading"><div><span className="eyebrow">YOUR NEXT TASK</span><h2>{form.id?'작업 수정':'새 작업 등록'}</h2></div><button type="button" className="icon-button" aria-label="작업 등록 닫기" onClick={()=>setForm(undefined)}><X size={20}/></button></div><label>작업내용 <input autoFocus required maxLength={200} placeholder="어떤 작업을 진행하나요?" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><div className="form-grid"><label>담당 파트<select aria-label="담당 파트" value={form.part} onChange={e=>{const rule=s.rules.find(r=>r.part===e.target.value)!;setForm({...form,part:rule.part,assigneeId:rule.assigneeId,reviewerId:rule.reviewerId});}}>{s.rules.map(r=><option key={r.part}>{r.part}</option>)}</select></label><label>우선순위<select aria-label="우선순위" value={form.priority} onChange={e=>setForm({...form,priority:e.target.value as Task['priority']})}>{Object.entries(priorities).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>담당자<select aria-label="담당자" value={form.assigneeId} onChange={e=>setForm({...form,assigneeId:e.target.value})}>{s.members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>검토자<select aria-label="검토자" value={form.reviewerId} onChange={e=>setForm({...form,reviewerId:e.target.value})}>{s.members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>작업 지정일<input type="date" required value={form.assignedDate} onChange={e=>setForm({...form,assignedDate:e.target.value})}/></label><label>마감일<input type="date" min={form.assignedDate} value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label></div><p className="form-hint">파트를 선택하면 기본 담당자와 검토자가 자동 배정됩니다.</p><label>설명<textarea maxLength={10000} rows={3} placeholder="완료 조건이나 참고 내용을 적어 주세요." value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="modal-footer"><span><HardDrive size={14}/>내 컴퓨터에 저장</span><button type="submit" className="primary" disabled={busy}>{busy?'저장 중…':'작업 저장'}<ArrowRight size={16}/></button></div></form></div>}
    {alerts&&<div className="overlay" onClick={()=>setAlerts(false)}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-top"><h2>알림 미리보기</h2><button className="icon-button" onClick={()=>setAlerts(false)} aria-label="알림 닫기"><X size={20}/></button></div><p className="muted">Discord 연결 전의 로컬 이벤트 목록입니다. 실제 알림은 전송되지 않습니다.</p>{!s.notifications.length?<div className="empty-panel"><Bell size={28}/><p>작업을 등록하거나 상태를 변경해 보세요.</p></div>:s.notifications.map(n=>{const payload=JSON.parse(n.payloadJson);return <div className="notification" key={n.id}><span className="part-tag">미리보기</span><h3>{payload.title}</h3><p>{n.eventType==='task.created'?'새 작업 등록':stages.find(st=>st.id===payload.status)?.label} → {person(n.recipientId).name}</p><small>{new Date(n.createdAt).toLocaleString('ko-KR')}</small></div>;})}</aside></div>}
    {conflicts&&<div className="overlay modal-overlay"><div className="modal"><div className="modal-heading"><h2>통합 전 확인이 필요해요</h2><button className="icon-button" onClick={()=>setConflicts(undefined)}><X size={20}/></button></div><p className="muted">데이터는 변경하지 않았습니다. 양쪽 변경을 확인하고 통합본을 조정해 주세요.</p>{conflicts.map((c,i)=><div className="reason-box" key={i}><b>{c.title} · {c.field}</b><p>내 변경: {c.local}<br/>통합본: {c.remote}</p></div>)}</div></div>}
    {toast&&<div className="toast" role="status"><Circle size={15}/>{toast}<button onClick={()=>setToast('')}><X size={14}/></button></div>}
  </div>;
}



